# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import agent_pb2 as agent__pb2


class AgentServiceStub(object):
    """AgentService defines the gRPC contract between the Go gateway and Python agent service.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Chat = channel.unary_stream(
                '/agent.v1.AgentService/Chat',
                request_serializer=agent__pb2.ChatRequest.SerializeToString,
                response_deserializer=agent__pb2.ChatEvent.FromString,
                )
        self.UploadPaper = channel.unary_unary(
                '/agent.v1.AgentService/UploadPaper',
                request_serializer=agent__pb2.UploadPaperRequest.SerializeToString,
                response_deserializer=agent__pb2.UploadPaperResponse.FromString,
                )
        self.HealthCheck = channel.unary_unary(
                '/agent.v1.AgentService/HealthCheck',
                request_serializer=agent__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=agent__pb2.HealthCheckResponse.FromString,
                )


class AgentServiceServicer(object):
    """AgentService defines the gRPC contract between the Go gateway and Python agent service.
    """

    def Chat(self, request, context):
        """Chat accepts one user message and streams back token/status events.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadPaper(self, request, context):
        """UploadPaper accepts raw file content and returns parsing metadata.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """HealthCheck reports service readiness and dependent service status.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Chat': grpc.unary_stream_rpc_method_handler(
                    servicer.Chat,
                    request_deserializer=agent__pb2.ChatRequest.FromString,
                    response_serializer=agent__pb2.ChatEvent.SerializeToString,
            ),
            'UploadPaper': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadPaper,
                    request_deserializer=agent__pb2.UploadPaperRequest.FromString,
                    response_serializer=agent__pb2.UploadPaperResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=agent__pb2.HealthCheckRequest.FromString,
                    response_serializer=agent__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agent.v1.AgentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AgentService(object):
    """AgentService defines the gRPC contract between the Go gateway and Python agent service.
    """

    @staticmethod
    def Chat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/agent.v1.AgentService/Chat',
            agent__pb2.ChatRequest.SerializeToString,
            agent__pb2.ChatEvent.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UploadPaper(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/agent.v1.AgentService/UploadPaper',
            agent__pb2.UploadPaperRequest.SerializeToString,
            agent__pb2.UploadPaperResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/agent.v1.AgentService/HealthCheck',
            agent__pb2.HealthCheckRequest.SerializeToString,
            agent__pb2.HealthCheckResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
